/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SuiFlextext {
        "maxSize": number;
        "minSize": number;
    }
    interface SuiNav {
        "autoHide": number;
    }
    interface SuiOverlay {
        "close": (cb?: () => any) => Promise<void>;
        "open": (cb?: () => any) => Promise<unknown>;
        "position": string;
        "transitionTime": string;
    }
    interface SuiTextarea {
        "disabled": boolean;
        "el": HTMLTextAreaElement;
        "value": string;
    }
    interface SuiTooltip {
    }
}
declare global {
    interface HTMLSuiFlextextElement extends Components.SuiFlextext, HTMLStencilElement {
    }
    var HTMLSuiFlextextElement: {
        prototype: HTMLSuiFlextextElement;
        new (): HTMLSuiFlextextElement;
    };
    interface HTMLSuiNavElement extends Components.SuiNav, HTMLStencilElement {
    }
    var HTMLSuiNavElement: {
        prototype: HTMLSuiNavElement;
        new (): HTMLSuiNavElement;
    };
    interface HTMLSuiOverlayElement extends Components.SuiOverlay, HTMLStencilElement {
    }
    var HTMLSuiOverlayElement: {
        prototype: HTMLSuiOverlayElement;
        new (): HTMLSuiOverlayElement;
    };
    interface HTMLSuiTextareaElement extends Components.SuiTextarea, HTMLStencilElement {
    }
    var HTMLSuiTextareaElement: {
        prototype: HTMLSuiTextareaElement;
        new (): HTMLSuiTextareaElement;
    };
    interface HTMLSuiTooltipElement extends Components.SuiTooltip, HTMLStencilElement {
    }
    var HTMLSuiTooltipElement: {
        prototype: HTMLSuiTooltipElement;
        new (): HTMLSuiTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "sui-flextext": HTMLSuiFlextextElement;
        "sui-nav": HTMLSuiNavElement;
        "sui-overlay": HTMLSuiOverlayElement;
        "sui-textarea": HTMLSuiTextareaElement;
        "sui-tooltip": HTMLSuiTooltipElement;
    }
}
declare namespace LocalJSX {
    interface SuiFlextext {
        "maxSize"?: number;
        "minSize"?: number;
    }
    interface SuiNav {
        "autoHide"?: number;
    }
    interface SuiOverlay {
        "position"?: string;
        "transitionTime"?: string;
    }
    interface SuiTextarea {
        "disabled"?: boolean;
        "el"?: HTMLTextAreaElement;
        "value"?: string;
    }
    interface SuiTooltip {
    }
    interface IntrinsicElements {
        "sui-flextext": SuiFlextext;
        "sui-nav": SuiNav;
        "sui-overlay": SuiOverlay;
        "sui-textarea": SuiTextarea;
        "sui-tooltip": SuiTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sui-flextext": LocalJSX.SuiFlextext & JSXBase.HTMLAttributes<HTMLSuiFlextextElement>;
            "sui-nav": LocalJSX.SuiNav & JSXBase.HTMLAttributes<HTMLSuiNavElement>;
            "sui-overlay": LocalJSX.SuiOverlay & JSXBase.HTMLAttributes<HTMLSuiOverlayElement>;
            "sui-textarea": LocalJSX.SuiTextarea & JSXBase.HTMLAttributes<HTMLSuiTextareaElement>;
            "sui-tooltip": LocalJSX.SuiTooltip & JSXBase.HTMLAttributes<HTMLSuiTooltipElement>;
        }
    }
}
