/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface SuiButton {
        "disabled": any;
    }
    interface SuiOverlay {
        "close": () => Promise<void>;
        "from": string;
        "open": () => Promise<void>;
        "show": boolean;
    }
    interface SuiSticky {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLSuiButtonElement extends Components.SuiButton, HTMLStencilElement {
    }
    var HTMLSuiButtonElement: {
        prototype: HTMLSuiButtonElement;
        new (): HTMLSuiButtonElement;
    };
    interface HTMLSuiOverlayElement extends Components.SuiOverlay, HTMLStencilElement {
    }
    var HTMLSuiOverlayElement: {
        prototype: HTMLSuiOverlayElement;
        new (): HTMLSuiOverlayElement;
    };
    interface HTMLSuiStickyElement extends Components.SuiSticky, HTMLStencilElement {
    }
    var HTMLSuiStickyElement: {
        prototype: HTMLSuiStickyElement;
        new (): HTMLSuiStickyElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "sui-button": HTMLSuiButtonElement;
        "sui-overlay": HTMLSuiOverlayElement;
        "sui-sticky": HTMLSuiStickyElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface SuiButton {
        "disabled"?: any;
    }
    interface SuiOverlay {
        "from"?: string;
        "show"?: boolean;
    }
    interface SuiSticky {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "sui-button": SuiButton;
        "sui-overlay": SuiOverlay;
        "sui-sticky": SuiSticky;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "sui-button": LocalJSX.SuiButton & JSXBase.HTMLAttributes<HTMLSuiButtonElement>;
            "sui-overlay": LocalJSX.SuiOverlay & JSXBase.HTMLAttributes<HTMLSuiOverlayElement>;
            "sui-sticky": LocalJSX.SuiSticky & JSXBase.HTMLAttributes<HTMLSuiStickyElement>;
        }
    }
}
